CREATE TABLE blogs
(
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(255) NOT NULL,
    imgUrl VARCHAR(255) NOT NULL,
    published TINYINT, 
    creatorId VARCHAR (255) NOT NULL
    PRIMARY KEY (Id)
);

CREATE TABLE comments
(
    Id INT NOT NULL AUTO_INCREMENT,
    CreatorId VARCHAR (255) NOT NULL,
    Body VARCHAR(255) NOT NULL,
    Blog VARCHAR(255) NOT NULL,


);

CREATE TABLE profiles
(
    id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    picture VARCHAR(255),
    PRIMARY KEY (id)
);