CREATE TABLE blogs
(
    Id INT NOT NULL AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Body VARCHAR(255) NOT NULL,
    imgUrl VARCHAR(255) NOT NULL,
    published TINYINT, 
    CreatorId VARCHAR (255) NOT NULL
)

CREATE TABLE comments
(
    Id INT NOT NULL AUTO_INCREMENT,
    CreatorId VARCHAR (255) NOT NULL,
    Body VARCHAR(255) NOT NULL,
    Blog VARCHAR(255) NOT NULL

)